### ISSUE TITLE
Integration mit Gruppenbildung

### ISSUE THREAD

**Issue by ChUrl** [hhu-propra2/abschlussprojekt-fixlater#100]
Jo Leute, ich wollte mal fragen wie ihr bei euch die Integration mit Gruppen handhabt (falls ihr sowas macht), damit wir wissen welche Informationen wir über unsere Api bereitstellen müssen. Wär also schön zu wissen ob ihr zum Beispiel eine Funktion zum allgemeinen Datenabgleich braucht, oder nur speziellere Anfragen nach einzelnen Gruppen (z.B.) stellt. Außerdem wollen wir wissen was für Informationen über Gruppen ihr bei euch verwendet (sowas wie Titel, Teilnehmer oder so).

Wir stimmen unsere Api dann mit den Senioren ab und stellen nur die nötigen Funktionen bereit.

Wenn ihr sowas gar nicht braucht einfach ignorieren :)

**Comment by Marcel297** [comment]
Wir haben die Schnittstelle bei uns bereits implementiert. Wir verwenden die bereitgestellte Anfrage updateGroups, holen uns dadurch die geänderten Gruppen und speichern diese. Bei uns sind dann GruppeId, Titel der Gruppe und Benutzer gespeichert. 
Können bei euch die Titel der Gruppen geändert werden? 
Wenn Ja: bitte mitteilen, wir müssen etwas ändern. 
Wenn Nein: wir brauchen nichts ändern

**Comment by ChUrl** [comment]
Ja, die Gruppentitel können sich ändern. Ihr würdet diese dann bei einem updateGroups aufruf erhalten, das heißt wenn ihr einen Datenabgleich macht bekommt ihr die neuen Titel.

**Comment by Marcel297** [comment]
Werden dann beim updateGroups auch alle Mitglieder dieser Gruppe mitgeliefert? Das würde uns einiges leichter machen mit der Änderung der Daten.

**Comment by lenue100** [comment]
Ich hätte zu der API auch noch eine Frage. Wenn wir das updateGroups anfragen, und es hat sich seit dem Status, der übergeben wurde, nichts geändert, was genau bekommt man dann zurück? Für unsere Tests bin ich davon ausgegangen, dass das Attribut groupList ein leeres JSON Array ist und der Status der gleiche ist wie der, den man übergeben hat, aber ich wollte dennoch fragen, ob das auch bei euch der Fall ist?

**Comment by ChUrl** [comment]
Ja, so wie du das in den Tests gemacht hast ist es bis jetzt richtig.

Falls sich daran irgendwas ändert (nachdem wir uns mit der anderen Gruppenbildung abgesprochen haben) sage ich nochmal bescheid, aber ich denke das passt

**Comment by ChUrl** [comment]
> Werden dann beim updateGroups auch alle Mitglieder dieser Gruppe mitgeliefert? Das würde uns einiges leichter machen mit der Änderung der Daten.

Das weiß ich leider erst Montag. Bis jetzt ist das bei uns zwar der Fall, aber da wir uns noch mit der anderen Gruppe absprechen, weiß ich nicht ob sich da noch was ändert

**Comment by lenue100** [comment]
> 
> 
> > Werden dann beim updateGroups auch alle Mitglieder dieser Gruppe mitgeliefert? Das würde uns einiges leichter machen mit der Änderung der Daten.
> 
> Das weiß ich leider erst Montag. Bis jetzt ist das bei uns zwar der Fall, aber da wir uns noch mit der anderen Gruppe absprechen, weiß ich nicht ob sich da noch was ändert

Es würde meiner Meinung nach Sinn ergeben, das so zu machen. Ihr speichert in eurer Datenbank so wie ich das von den Tutoren mitbekommen habe nur die Änderungen an den Gruppen, also würdet ihr zwar getrennt speichern, wenn sich der Gruppenname ändert und ein neuer Nutzer die Gruppe betritt (oder ein Nutzer die Gruppe verlässt), allerdings kann es ja vorkommen, dass solche Änderungen an einer Gruppe in einem geringen Zeitraum passieren, sodass wir die Neuerungen nur nach beiden Änderungen abfragen. Dann müssen ja in der JSON beide Informationen gleichzeitig enthalten sein, und das ginge am einfachsten, wenn man immer alle Member der Gruppe mitschickt.

**Comment by ChUrl** [comment]
Ok also wie es aussieht ist es gar nicht nötig, dass beide Gruppenbildung-Gruppen eine einheitliche Schnittstelle bereitstellen. Je nachdem mit welcher Gruppe ihr gearbeitet habt könnt ihr das einfach beibehalten

**Comment by lenue100** [comment]
Okay, wenn sich nichts ändert, dann passt alles
